Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,13 +1,20 @@
-name: Gitea Actions Demo
-on: [push]
+name: Do Not Merge
+
+on:
+  # Check label at every push in a feature branch
+  push:
+    branches-ignore:
+      - main
+  # Check label during the lifetime of a pull request
+  pull_request:
+    types: [synchronize, opened, reopened, labeled, unlabeled]
+
 jobs:
-  build-docker:
-    runs-on: ubuntu-latest
+  do-not-merge:
+    runs-on: ubuntu-22.04
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Docker build push
-        uses: ./.github/actions/action-docker-build-push
-
-      - run: echo The end
+      - name: Fail if PR is labeled with do not merge
+        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
+        run: |
+          echo "This PR can't be merged, due to the 'do-not-merge' label."
+          exit 1
